name: 'sync_ftp_folder_action'
description: 'Sync a folder to an FTP server'
author: 'aps-m'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'folder'
  color: 'orange'

# Define your inputs here.
inputs:
  host:
    description: 'FTP server host'
    required: true
    default: 'localhost'

  port:
    description: 'FTP server port'
    required: true
    default: 21

  user:
    description: 'FTP authorization user'
    required: true
    default: 'anonymous'

  password:
    description: 'FTP authorization password'
    required: true
    default: ''

  timeout:
    description: 'Action timeout in milliseconds'
    required: true
    default: 10000

  src_path:
    description: 'Local folder path'
    required: true

  dst_path:
    description: 'Remote folder path'
    required: true
    default: '.'

runs:
  using: node20
  main: dist/index.js
